import { generateFollowUpDraft } from "@edagent/ai";
import { database } from "@edagent/database";
import type { BackgroundJob } from "@edagent/domain";
import { getEmailProvider } from "@edagent/integrations";
import { buildCompanyProfile } from "../services/company-profile.js";
import { deliverQueuedEmailMessage } from "../services/email-delivery.js";

export async function handleRunFollowUpSchedulerJob(job: BackgroundJob): Promise<void> {
  const dueBefore = String(job.payload.dueBefore ?? new Date().toISOString());
  const pendingMessages = await database.getPendingFollowUpMessages(dueBefore);
  let createdCount = 0;

  for (const message of pendingMessages) {
    const draft = message.draftId ? await database.getMessageDraftById(message.draftId) : null;
    const profileBundle = await buildCompanyProfile(message.companyId);
    if (!profileBundle?.primaryContact?.email) {
      continue;
    }

    const tone = draft?.tone ?? "neutral";
    const followUpDraft = generateFollowUpDraft({
      ...profileBundle.profile,
      tone,
      contactName: profileBundle.primaryContact.fullName,
      contactTitle: profileBundle.primaryContact.title
    });

    const followUpInput: {
      companyId: string;
      contactId: string;
      parentMessageId: string;
      channel: "email";
      kind: "follow-up-email";
      provider: string;
      status: "queued";
      subject: string;
      body: string;
      draftId?: string;
      campaignId?: string;
    } = {
      companyId: message.companyId,
      contactId: message.contactId,
      parentMessageId: message.id,
      channel: "email",
      kind: "follow-up-email",
      provider: getEmailProvider().name,
      status: "queued",
      subject: followUpDraft.subject,
      body: followUpDraft.body
    };
    if (message.draftId) {
      followUpInput.draftId = message.draftId;
    }
    if (message.campaignId) {
      followUpInput.campaignId = message.campaignId;
    }

    const followUpMessage = await database.createMessage(followUpInput);

    await database.createMessageEvent({
      messageId: message.id,
      type: "follow-up-scheduled",
      payload: {
        followUpMessageId: followUpMessage.id
      }
    });
    await database.createMessageEvent({
      messageId: followUpMessage.id,
      type: "queued",
      payload: {
        parentMessageId: message.id,
        autoGenerated: true
      }
    });

    const delivery = await deliverQueuedEmailMessage({
      queuedMessageId: followUpMessage.id,
      to: profileBundle.primaryContact.email,
      subject: followUpDraft.subject,
      body: followUpDraft.body,
      companyId: message.companyId,
      memoryEventTypeOnSuccess: "follow_up_sent",
      memoryPayloadOnSuccess: {
        parentMessageId: message.id,
        tone
      },
      memoryEventTypeOnFailure: "follow_up_failed",
      memoryPayloadOnFailure: {
        parentMessageId: message.id,
        tone
      },
      eventPayloadOnSent: {
        parentMessageId: message.id,
        autoGenerated: true
      },
      eventPayloadOnDelivered: {
        parentMessageId: message.id,
        autoGenerated: true
      }
    });

    if (delivery.status === "delivered") {
      createdCount += 1;
    } else {
      console.error(
        JSON.stringify({
          scope: "worker.follow_up",
          status: "failed",
          jobId: job.id,
          messageId: followUpMessage.id,
          parentMessageId: message.id,
          message: delivery.message
        })
      );
    }
  }

  console.log(
    JSON.stringify({
      scope: "worker.follow_up",
      status: "completed",
      jobId: job.id,
      dueBefore,
      createdCount
    })
  );
}
